import { motion } from 'framer-motion';
import { Brain, PhoneCall, Inbox, Workflow, TrendingUp, Users, BarChart3, Bot, Sparkles } from 'lucide-react';
import anasChatLogo from '@/assets/anaschat-logo.png'; // Using the existing logo for AnaOS

const features = [
  {
    title: 'AI Knowledge Base',
    description: 'Train on your URLs & PDFs. Auto-syncs and answers intelligently like your best employee.',
    icon: Brain,
    color: 'text-blue-400',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20',
  },
  {
    title: 'Autonomous Voice AI',
    description: 'Human-like inbound & outbound AI calls. Missed call recovery via WhatsApp & SMS.',
    icon: PhoneCall,
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/20',
  },
  {
    title: 'The Unified Inbox',
    description: 'Omnichannel command center. Auto-replies in 1 sec with seamless human handoff.',
    icon: Inbox,
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
  },
  {
    title: 'Workflow Builder',
    description: '100+ integrations. Drag-and-drop or prompt-based automation for your business tasks.',
    icon: Workflow,
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/20',
  },
  {
    title: 'Growth AI & Marketing',
    description: 'Social media auto-pilot. Capture leads and auto-sync them directly with your CRM.',
    icon: TrendingUp,
    color: 'text-pink-400',
    bg: 'bg-pink-500/10',
    border: 'border-pink-500/20',
  },
  {
    title: 'Smart CRM & Contacts',
    description: 'Automatic customer profiling, lead data saving, and AI calendar booking on the fly.',
    icon: Users,
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/20',
  },
  {
    title: 'Performance & ROI',
    description: 'Real-time dashboard. Live tracking of leads, responses, and revenue generated by AnaOS.',
    icon: BarChart3,
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/20',
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { type: 'spring', stiffness: 100 },
  },
};

export function AnaOSSection() {
  return (
    <section className="py-24 relative overflow-hidden bg-black">
      {/* Background Gradients */}
      <div className="absolute top-0 left-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-[120px] pointer-events-none" />
      
      <div className="container mx-auto px-6 relative z-10">
        
        {/* Header Section */}
        <div className="text-center max-w-4xl mx-auto mb-16">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="flex items-center justify-center gap-3 mb-6"
          >
            <div className="w-16 h-16 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center backdrop-blur-sm p-3 shadow-[0_0_30px_rgba(6,182,212,0.3)]">
              <img src={anasChatLogo} alt="AnaOS Logo" className="w-full h-full object-contain" />
            </div>
            <h2 className="text-4xl md:text-5xl font-bold text-white tracking-tight">
              Ana OS
            </h2>
          </motion.div>
          
          <motion.h3 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-2xl md:text-3xl font-semibold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500 mb-6 leading-tight"
          >
            Replace 10 different apps with 1 Intelligent AI Brain.
          </motion.h3>
          
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-gray-400 text-lg md:text-xl"
          >
            Don't just chat. Automate your entire business from WhatsApp to Voice Calls. 
            Sleep well while AnaOS answers your customers, books appointments, and closes sales 24/7.
          </motion.p>
        </div>

        {/* Features Grid */}
        <motion.div 
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
        >
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              variants={itemVariants}
              className={`group relative p-6 rounded-3xl bg-white/[0.02] border ${feature.border} hover:bg-white/[0.04] transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:shadow-cyan-500/5`}
            >
              <div className={`w-12 h-12 rounded-2xl ${feature.bg} flex items-center justify-center mb-6 transition-transform duration-300 group-hover:scale-110`}>
                <feature.icon className={`w-6 h-6 ${feature.color}`} />
              </div>
              <h4 className="text-xl font-bold text-white mb-3 flex items-center gap-2">
                {feature.title}
                {index === 1 && <Sparkles className="w-4 h-4 text-cyan-400" />}
                {index === 3 && <Bot className="w-4 h-4 text-purple-400" />}
              </h4>
              <p className="text-gray-400 leading-relaxed text-sm">
                {feature.description}
              </p>
            </motion.div>
          ))}
          
          {/* Custom CTA Card to complete the grid nicely if there are 7 items */}
          <motion.div
            variants={itemVariants}
            className="group relative p-6 rounded-3xl bg-gradient-to-br from-cyan-500/20 to-blue-600/20 border border-cyan-500/30 flex flex-col justify-center items-center text-center hover:from-cyan-500/30 hover:to-blue-600/30 transition-all duration-300"
          >
            <h4 className="text-2xl font-bold text-white mb-2">Ready to Automate?</h4>
            <p className="text-cyan-100 text-sm mb-6">Deploy AnaOS for your business today.</p>
            <a href="https://anaos.io/" target="_blank" rel="noopener noreferrer" className="bg-white text-black px-6 py-3 rounded-xl font-semibold text-sm hover:bg-cyan-50 transition-colors shadow-[0_0_20px_rgba(255,255,255,0.2)]">
              Get Started with AnaOS
            </a>
          </motion.div>
        </motion.div>

      </div>
    </section>
  );
}
